gensong_mujoco:
  ros__parameters:
    model_path: ""
    viewer: true
    simulation_hz: 500.0
    position_gain: 1200.0
    velocity_gain: 120.0
    leg_position_gain: 8000.0
    leg_velocity_gain: 400.0
    waist_position_gain: 5000.0
    waist_velocity_gain: 500.0
    arm_position_gain: 4000.0
    arm_velocity_gain: 250.0
    wrist_position_gain: 1500.0
    wrist_velocity_gain: 120.0
    torque_limit: 300.0
    camera_hz: 30.0
    camera_width: 640
    camera_height: 480
    color_topic: /gensong/camera/color/image_raw
    depth_topic: /gensong/camera/depth/image_raw
    color_info_topic: /gensong/camera/color/camera_info
    depth_info_topic: /gensong/camera/depth/camera_info
